create type "public"."currency" as enum ('USD', 'KRW');

create type "public"."order_status" as enum ('success', 'on-hold', 'pending', 'failed', 'cancel');

create type "public"."payment_cycle" as enum ('none', 'day', 'week', 'month');

create type "public"."pg" as enum ('paypal', 'apple', 'google', 'toss', 'naver');

create table "public"."order" (
    "id" bigint generated by default as identity not null,
    "subscriptions_id" bigint,
    "user_id" bigint,
    "retry_count" bigint,
    "book_payment_id" text,
    "result_status" order_status,
    "transaction_id" text,
    "notes" text,
    "updated_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."order" enable row level security;

create table "public"."product_payment_type" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "platform" text,
    "payment_cycle" payment_cycle not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."product_payment_type" enable row level security;

create table "public"."prouduct_payment_type_price" (
    "id" bigint generated by default as identity not null,
    "product_payment_type_id" bigint,
    "amount" numeric not null,
    "currency" currency not null,
    "end_date" timestamp with time zone not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."prouduct_payment_type_price" enable row level security;

create table "public"."subscriptions" (
    "id" bigint generated by default as identity not null,
    "product_payment_type_price_id" bigint,
    "issue_id" text,
    "billing_key" text,
    "user_id" bigint,
    "pg" pg not null,
    "billing_date" timestamp with time zone not null,
    "updated_at" timestamp with time zone not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."subscriptions" enable row level security;

CREATE UNIQUE INDEX order_pkey ON public."order" USING btree (id);

CREATE UNIQUE INDEX product_payment_type_pkey ON public.product_payment_type USING btree (id);

CREATE UNIQUE INDEX prouduct_payment_type_price_pkey ON public.prouduct_payment_type_price USING btree (id);

CREATE UNIQUE INDEX subscriptions_pkey ON public.subscriptions USING btree (id);

alter table "public"."order" add constraint "order_pkey" PRIMARY KEY using index "order_pkey";

alter table "public"."product_payment_type" add constraint "product_payment_type_pkey" PRIMARY KEY using index "product_payment_type_pkey";

alter table "public"."prouduct_payment_type_price" add constraint "prouduct_payment_type_price_pkey" PRIMARY KEY using index "prouduct_payment_type_price_pkey";

alter table "public"."subscriptions" add constraint "subscriptions_pkey" PRIMARY KEY using index "subscriptions_pkey";

alter table "public"."order" add constraint "public_order_subscriptions_id_fkey" FOREIGN KEY (subscriptions_id) REFERENCES subscriptions(id) not valid;

alter table "public"."order" validate constraint "public_order_subscriptions_id_fkey";

alter table "public"."order" add constraint "public_order_user_id_fkey" FOREIGN KEY (user_id) REFERENCES user_info(id) not valid;

alter table "public"."order" validate constraint "public_order_user_id_fkey";

alter table "public"."prouduct_payment_type_price" add constraint "public_prouduct_payment_type_price_product_payment_type_id_fkey" FOREIGN KEY (product_payment_type_id) REFERENCES product_payment_type(id) not valid;

alter table "public"."prouduct_payment_type_price" validate constraint "public_prouduct_payment_type_price_product_payment_type_id_fkey";

alter table "public"."subscriptions" add constraint "public_subscriptions_product_payment_type_price_id_fkey" FOREIGN KEY (product_payment_type_price_id) REFERENCES prouduct_payment_type_price(id) not valid;

alter table "public"."subscriptions" validate constraint "public_subscriptions_product_payment_type_price_id_fkey";

alter table "public"."subscriptions" add constraint "public_subscriptions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES user_info(id) not valid;

alter table "public"."subscriptions" validate constraint "public_subscriptions_user_id_fkey";

grant delete on table "public"."order" to "anon";

grant insert on table "public"."order" to "anon";

grant references on table "public"."order" to "anon";

grant select on table "public"."order" to "anon";

grant trigger on table "public"."order" to "anon";

grant truncate on table "public"."order" to "anon";

grant update on table "public"."order" to "anon";

grant delete on table "public"."order" to "authenticated";

grant insert on table "public"."order" to "authenticated";

grant references on table "public"."order" to "authenticated";

grant select on table "public"."order" to "authenticated";

grant trigger on table "public"."order" to "authenticated";

grant truncate on table "public"."order" to "authenticated";

grant update on table "public"."order" to "authenticated";

grant delete on table "public"."order" to "service_role";

grant insert on table "public"."order" to "service_role";

grant references on table "public"."order" to "service_role";

grant select on table "public"."order" to "service_role";

grant trigger on table "public"."order" to "service_role";

grant truncate on table "public"."order" to "service_role";

grant update on table "public"."order" to "service_role";

grant delete on table "public"."product_payment_type" to "anon";

grant insert on table "public"."product_payment_type" to "anon";

grant references on table "public"."product_payment_type" to "anon";

grant select on table "public"."product_payment_type" to "anon";

grant trigger on table "public"."product_payment_type" to "anon";

grant truncate on table "public"."product_payment_type" to "anon";

grant update on table "public"."product_payment_type" to "anon";

grant delete on table "public"."product_payment_type" to "authenticated";

grant insert on table "public"."product_payment_type" to "authenticated";

grant references on table "public"."product_payment_type" to "authenticated";

grant select on table "public"."product_payment_type" to "authenticated";

grant trigger on table "public"."product_payment_type" to "authenticated";

grant truncate on table "public"."product_payment_type" to "authenticated";

grant update on table "public"."product_payment_type" to "authenticated";

grant delete on table "public"."product_payment_type" to "service_role";

grant insert on table "public"."product_payment_type" to "service_role";

grant references on table "public"."product_payment_type" to "service_role";

grant select on table "public"."product_payment_type" to "service_role";

grant trigger on table "public"."product_payment_type" to "service_role";

grant truncate on table "public"."product_payment_type" to "service_role";

grant update on table "public"."product_payment_type" to "service_role";

grant delete on table "public"."prouduct_payment_type_price" to "anon";

grant insert on table "public"."prouduct_payment_type_price" to "anon";

grant references on table "public"."prouduct_payment_type_price" to "anon";

grant select on table "public"."prouduct_payment_type_price" to "anon";

grant trigger on table "public"."prouduct_payment_type_price" to "anon";

grant truncate on table "public"."prouduct_payment_type_price" to "anon";

grant update on table "public"."prouduct_payment_type_price" to "anon";

grant delete on table "public"."prouduct_payment_type_price" to "authenticated";

grant insert on table "public"."prouduct_payment_type_price" to "authenticated";

grant references on table "public"."prouduct_payment_type_price" to "authenticated";

grant select on table "public"."prouduct_payment_type_price" to "authenticated";

grant trigger on table "public"."prouduct_payment_type_price" to "authenticated";

grant truncate on table "public"."prouduct_payment_type_price" to "authenticated";

grant update on table "public"."prouduct_payment_type_price" to "authenticated";

grant delete on table "public"."prouduct_payment_type_price" to "service_role";

grant insert on table "public"."prouduct_payment_type_price" to "service_role";

grant references on table "public"."prouduct_payment_type_price" to "service_role";

grant select on table "public"."prouduct_payment_type_price" to "service_role";

grant trigger on table "public"."prouduct_payment_type_price" to "service_role";

grant truncate on table "public"."prouduct_payment_type_price" to "service_role";

grant update on table "public"."prouduct_payment_type_price" to "service_role";

grant delete on table "public"."subscriptions" to "anon";

grant insert on table "public"."subscriptions" to "anon";

grant references on table "public"."subscriptions" to "anon";

grant select on table "public"."subscriptions" to "anon";

grant trigger on table "public"."subscriptions" to "anon";

grant truncate on table "public"."subscriptions" to "anon";

grant update on table "public"."subscriptions" to "anon";

grant delete on table "public"."subscriptions" to "authenticated";

grant insert on table "public"."subscriptions" to "authenticated";

grant references on table "public"."subscriptions" to "authenticated";

grant select on table "public"."subscriptions" to "authenticated";

grant trigger on table "public"."subscriptions" to "authenticated";

grant truncate on table "public"."subscriptions" to "authenticated";

grant update on table "public"."subscriptions" to "authenticated";

grant delete on table "public"."subscriptions" to "service_role";

grant insert on table "public"."subscriptions" to "service_role";

grant references on table "public"."subscriptions" to "service_role";

grant select on table "public"."subscriptions" to "service_role";

grant trigger on table "public"."subscriptions" to "service_role";

grant truncate on table "public"."subscriptions" to "service_role";

grant update on table "public"."subscriptions" to "service_role";


