create table "public"."beta_tester" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "registered_at" timestamp with time zone,
    "accepted" boolean default false,
    "user_id" uuid default auth.uid()
);


alter table "public"."beta_tester" enable row level security;

CREATE UNIQUE INDEX beta_tester_pkey ON public.beta_tester USING btree (id);

CREATE UNIQUE INDEX beta_tester_user_id_key ON public.beta_tester USING btree (user_id);

alter table "public"."beta_tester" add constraint "beta_tester_pkey" PRIMARY KEY using index "beta_tester_pkey";

alter table "public"."beta_tester" add constraint "beta_tester_user_id_key" UNIQUE using index "beta_tester_user_id_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.update_registered_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- accepted가 true로 변경되었는지 확인
    IF NEW.accepted = true THEN
        -- registered_at을 현재 시간으로 갱신
        NEW.registered_at = now();
    END IF;
    RETURN NEW;
END;
$function$
;

grant delete on table "public"."beta_tester" to "anon";

grant insert on table "public"."beta_tester" to "anon";

grant references on table "public"."beta_tester" to "anon";

grant select on table "public"."beta_tester" to "anon";

grant trigger on table "public"."beta_tester" to "anon";

grant truncate on table "public"."beta_tester" to "anon";

grant update on table "public"."beta_tester" to "anon";

grant delete on table "public"."beta_tester" to "authenticated";

grant insert on table "public"."beta_tester" to "authenticated";

grant references on table "public"."beta_tester" to "authenticated";

grant select on table "public"."beta_tester" to "authenticated";

grant trigger on table "public"."beta_tester" to "authenticated";

grant truncate on table "public"."beta_tester" to "authenticated";

grant update on table "public"."beta_tester" to "authenticated";

grant delete on table "public"."beta_tester" to "service_role";

grant insert on table "public"."beta_tester" to "service_role";

grant references on table "public"."beta_tester" to "service_role";

grant select on table "public"."beta_tester" to "service_role";

grant trigger on table "public"."beta_tester" to "service_role";

grant truncate on table "public"."beta_tester" to "service_role";

grant update on table "public"."beta_tester" to "service_role";

create policy "Enable insert for users based on email"
on "public"."beta_tester"
as permissive
for insert
to authenticated
with check ((user_id = auth.uid()));


create policy "Enable read access for all users"
on "public"."beta_tester"
as permissive
for select
to public
using (true);


create policy "Enable update for users based on email"
on "public"."beta_tester"
as permissive
for update
to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));


CREATE TRIGGER trigger_update_registered_at BEFORE UPDATE ON public.beta_tester FOR EACH ROW WHEN ((old.accepted IS DISTINCT FROM new.accepted)) EXECUTE FUNCTION update_registered_at();


