create table
  public.customers (
    id bigint generated by default as identity,
    name character varying(255) null,
    email character varying(255) null,
    constraint customers_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.billing_rates (
    id bigint generated by default as identity,
    api_end_point character varying(255) null,
    token_rate numeric(10, 2) null,
    call_rate numeric(10, 2) null,
    constraint billing_rates_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.products (
    id bigint generated always as identity,
    name character varying(255) null,
    description text null,
    price numeric(10, 2) null,
    is_subscription boolean null,
    constraint products_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.orders (
    id bigint generated always as identity,
    customer_id integer null,
    order_date timestamp with time zone null,
    total_amount numeric(10, 2) null,
    status text null,
    constraint orders_pkey primary key (id),
    constraint orders_customerid_fkey foreign key (customer_id) references customers (id)
  ) tablespace pg_default;


create table
  public.payment_information (
    id bigint generated by default as identity,
    customer_id bigint null,
    billing_key text null,
    payment_gateway text null,
    card_number text null,
    expiry_date timestamp with time zone null,
    cvv text null,
    billing_address text null,
    constraint payment_information_pkey primary key (id),
    constraint payment_information_customer_id_fkey foreign key (customer_id) references customers (id)
  ) tablespace pg_default;



create table
  public.payment_records (
    id bigint generated by default as identity,
    order_id integer null,
    payment_date timestamp with time zone null,
    amount numeric(10, 2) null,
    success boolean null,
    payment_method text null,
    constraint payment_records_pkey primary key (id),
    constraint payment_records_order_id_fkey foreign key (order_id) references orders (id)
  ) tablespace pg_default;

create table
  public.order_items (
    id bigint generated by default as identity,
    order_id integer null,
    product_id integer null,
    quantity integer null,
    price numeric(10, 2) null,
    constraint order_items_pkey primary key (id),
    constraint orderitems_orderid_fkey foreign key (order_id) references orders (id),
    constraint orderitems_productid_fkey foreign key (product_id) references products (id)
  ) tablespace pg_default;

create table
  public.subscriptions (
    id bigint generated by default as identity,
    order_item_id integer null,
    start_date timestamp with time zone null,
    end_date timestamp with time zone null,
    status text null,
    payment_info_id integer null,
    constraint subscriptions_pkey primary key (id),
    constraint subscriptions_order_item_id_fkey foreign key (order_item_id) references order_items (id),
    constraint subscriptions_payment_info_id_fkey foreign key (payment_info_id) references payment_information (id)
  ) tablespace pg_default;

create table
  public.billing (
    id bigint generated by default as identity,
    customer_id integer null,
    billing_date date null,
    billing_period_start date null,
    billing_period_end date null,
    total_amount_due numeric(10, 2) null,
    status character varying(50) null,
    constraint billing_pkey primary key (id),
    constraint billing_customerid_fkey foreign key (customer_id) references customers (id)
  ) tablespace pg_default;

create table
  public.api_usage (
    id bigint generated by default as identity,
    customer_id integer null,
    api_end_point character varying(255) null,
    usage_time_stamp timestamp with time zone null,
    token_used integer null,
    calls_made integer null,
    constraint api_usage_pkey primary key (id),
    constraint apiusage_customerid_fkey foreign key (customer_id) references customers (id)
  ) tablespace pg_default;
